# Lab 01: Setup computing environment

### (10 pts) Task 1: Run this block of code to ensure that your dependencies are installed

In [1]:
import numpy as np
import tensorflow
import torch

### (10 pts) Task 2: Complete the function `linear_transformation()` by implementing a matrix multiplication between the data matrix, `X` of size `M x N`, and the tensor, `W` of size `N x N` (an identity matrix).

In [2]:
def linear_transformation(X, W):
    """
    Parameters
    ----------
    X: np.array (M x N)
        Data matrix
    W: np.array(N x N)
        Linear transformation
    Returns
    -------
    X_prime: np.array (M x N)
    """
    return (np.dot(X,W))
    pass

In [3]:
W = np.identity(10)
X = np.random.random((300, 10))

In [4]:
X_tx = linear_transformation(X, W)
assert (X_tx == X).all()
print(X_tx)

[[0.01246363 0.97540493 0.4195688  ... 0.10409968 0.08635803 0.01337821]
 [0.92388748 0.64677916 0.76620136 ... 0.31950858 0.52164367 0.87655868]
 [0.67305265 0.84023    0.34998356 ... 0.82944544 0.90201357 0.57208744]
 ...
 [0.83897925 0.28528432 0.8288042  ... 0.28507032 0.39034505 0.35050899]
 [0.54861905 0.00287193 0.60885324 ... 0.67720253 0.2205866  0.2362753 ]
 [0.9707369  0.02173896 0.44219371 ... 0.22564789 0.01424309 0.12107482]]
